# Generated by Django 6.0.3 on 2026-03-23 19:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Tytuł')),
                ('description', models.TextField(verbose_name='Opis')),
                ('category', models.CharField(choices=[('motocykl', 'Motocykl'), ('osobowy', 'Osobowy'), ('ciezarowy', 'Ciężarowy')], max_length=20, verbose_name='Kategoria')),
                ('brand', models.CharField(max_length=100, verbose_name='Marka')),
                ('model', models.CharField(max_length=100, verbose_name='Model')),
                ('year', models.PositiveIntegerField(verbose_name='Rok produkcji')),
                ('mileage', models.PositiveIntegerField(verbose_name='Przebieg (km)')),
                ('engine_capacity', models.PositiveIntegerField(verbose_name='Pojemność skokowa (cm³)')),
                ('power', models.PositiveIntegerField(verbose_name='Moc (KM)')),
                ('fuel_type', models.CharField(choices=[('benzyna', 'Benzyna'), ('diesel', 'Diesel'), ('lpg', 'LPG')], max_length=10, verbose_name='Rodzaj paliwa')),
                ('image', models.ImageField(blank=True, null=True, upload_to='vehicles/%Y/%m/%d', verbose_name='Zdjęcie')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='Data dodania')),
                ('published_at', models.DateField(blank=True, null=True, verbose_name='Data publikacji')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Usunięty')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicles', to=settings.AUTH_USER_MODEL, verbose_name='Użytkownik')),
            ],
            options={
                'verbose_name': 'Pojazd',
                'verbose_name_plural': 'Pojazdy',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VehicleImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='vehicles/gallery/%Y/%m/%d', verbose_name='Zdjęcie')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Data przesłania')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='MotoSell.vehicle', verbose_name='Pojazd')),
            ],
            options={
                'verbose_name': 'Zdjęcie pojazdu',
                'verbose_name_plural': 'Zdjęcia pojazdu',
            },
        ),
    ]
